version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: 'cimg/node:14.17.0'
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  version: 2
  test-dev:
    jobs:
      - test:
          filters:
            branches:
              only: dev